In [34]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)


#1. Data Exploration and Preprocessing

●	Begin by loading and exploring the "Alphabets_data.csv" dataset. Summarize its key features such as the number of samples, features, and classes.

●	Execute necessary data preprocessing steps including data normalization, managing missing values.

In [35]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense #Dense to add layers(hidden ,output)
from tensorflow.keras import Sequential #Sequential to add layers in sequence to initialize and model i.e. initially random weight will be assigned
from sklearn.metrics import classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

In [36]:
df=pd.read_csv('/content/Alphabets_data.csv')
df

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

In [37]:
num_samples = df.shape[0]
num_features = df.shape[1] - 1  # Exclude 'letter' column as it's the target
num_classes = df['letter'].nunique()

print(f"Number of samples: {num_samples}")
print(f"Number of features: {num_features}")
print(f"Number of classes (unique letters): {num_classes}")
print(f"Classes: {df['letter'].unique()}")

Number of samples: 20000
Number of features: 16
Number of classes (unique letters): 26
Classes: ['T' 'I' 'D' 'N' 'G' 'S' 'B' 'A' 'J' 'M' 'X' 'O' 'R' 'F' 'C' 'H' 'W' 'L'
 'P' 'E' 'V' 'Y' 'Q' 'U' 'K' 'Z']

In [38]:
df.isna().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [39]:
X = df.drop('letter', axis=1)
y = df['letter']

In [40]:
# Encode the target variable 'letter' into numerical labels
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print(f"Original unique classes: {label_encoder.classes_}")
print(f"Encoded labels (first 5): {y_encoded[:5]}")

Original unique classes: ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']
Encoded labels (first 5): [19  8  3 13  6]

In [41]:
df['letter'].value_counts()

letter
U    813
D    805
P    803
T    796
M    792
A    789
X    787
Y    786
N    783
Q    783
F    775
G    773
E    768
B    766
V    764
L    761
R    758
I    755
O    753
W    752
S    748
J    747
K    739
C    736
H    734
Z    734
Name: count, dtype: int64

#2. Model Implementation

●	Construct a basic ANN model using your chosen high-level neural network library. Ensure your model includes at least one hidden layer.

●	Divide the dataset into training and test sets.

●	Train your model on the training set and then use it to make predictions on the test set.

In [42]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

X_train shape: (16000, 16)
X_test shape: (4000, 16)
y_train shape: (16000,)
y_test shape: (4000,)

In [43]:
# Apply StandardScaler for normalization
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Features normalized successfully.")
print(f"First 5 rows of X_train_scaled:\n{X_train_scaled[:5]}")

Features normalized successfully.
First 5 rows of X_train_scaled:
[[-0.01291349 -0.01275171 -0.06013429 -0.16638781  0.22545989 -0.44203264
  -0.21256131 -0.60314772  0.76100746  1.08879289  0.59047067  0.51394072
  -0.01948363 -0.21675086  0.12044468  0.12215017]
 [-0.01291349 -0.01275171  0.43581861 -0.16638781  0.68208751 -0.44203264
   0.21739836 -0.60314772  0.76100746  1.08879289  0.59047067  0.51394072
  -0.01948363 -0.21675086  0.12044468 -0.49633169]
 [-0.53599158 -0.618174   -0.55608718 -1.04893543 -0.23116773  0.05041425
   0.21739836  0.13461945 -0.07532191 -0.51676332  0.2096754  -0.92625745
   0.83811784  0.43123377 -0.65897489 -1.11481354]
 [-0.01291349  0.89538173  0.43581861  0.71615981  1.13871514 -0.93447953
  -0.21256131  0.13461945  0.76100746 -0.91815237 -0.17111987  1.95413889
  -0.01948363 -0.21675086  0.89986424  0.74063202]
 [-0.01291349  0.89538173  0.43581861  1.15743362  0.22545989  0.54286114
   1.50727738 -0.9720313  -0.91165129 -1.72093047  1.35206121  0.51394072
  -0.01948363  1.72720301 -1.04868467  0.12215017]]

In [44]:
model = Sequential()

In [45]:
model.add(Dense(units=64, activation='relu', input_dim=X_train_scaled.shape[1])) # Hidden layer
model.add(Dense(units=num_classes, activation='softmax')) # Output layer for multi-class classification

In [46]:
model.compile(optimizer='adadelta', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [33]:
model.fit(X_train_scaled, y_train, epochs=100)
#epochs=100 means that the model will go throung the entire xtrain and ytrain dataset 100 times during traininf the model.
#epoch: backward and forward propagation will done for 100 times.
#the number of batcher per epoch = total number of sampes/ batch size (defalt is 32).
#50% training data =16000 samples,so batchs=16000/32 = 500.
#each batch is precessed in sequence during each epoch.
#and after all 500 batches are processed , one epoch is complete.

Epoch 1/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 2/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 3/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 4/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 5/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 6/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 7/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 8/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 9/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 10/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 11/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 12/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 13/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 14/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 15/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 16/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 17/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 18/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 19/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 20/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 21/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 22/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 23/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 24/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 25/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 26/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 27/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 28/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 29/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 30/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 31/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 32/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 33/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 34/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 35/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 36/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 37/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 38/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 39/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 40/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 41/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 42/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 43/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 44/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 45/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 46/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 47/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 48/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 49/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 50/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 51/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 52/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0400 - loss: nan
Epoch 53/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0400 - loss: nan
Epoch 54/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0400 - loss: nan
Epoch 55/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 56/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 57/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 58/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 59/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 60/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 61/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 62/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 63/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 64/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 65/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 66/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 67/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 68/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 69/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 70/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 71/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 72/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 73/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 74/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 75/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 76/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 77/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 78/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 79/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 80/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 81/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 82/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 83/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 84/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 85/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 86/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 87/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 88/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: nan
Epoch 89/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 90/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 91/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 92/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 93/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 94/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 95/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 96/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 97/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 98/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 99/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan
Epoch 100/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0400 - loss: nan

In [47]:
X_test_scaled

array([[-0.53599158, -0.31546285, -0.06013429, ..., -0.86473548,
         1.28957403, -1.11481354],
       [-0.01291349,  1.19809287,  0.43581861, ...,  1.72720301,
         1.28957403, -1.73329539],
       [-0.53599158, -0.92088514, -0.06013429, ..., -1.5127201 ,
        -0.65897489,  0.12215017],
       ...,
       [ 0.5101646 ,  0.89538173,  0.9317715 , ..., -0.21675086,
         0.12044468,  0.12215017],
       [-0.01291349, -0.618174  , -0.06013429, ...,  1.07921839,
         2.06899359, -1.73329539],
       [-1.05906966, -0.618174  , -0.55608718, ...,  1.72720301,
        -0.65897489,  0.12215017]])

In [48]:
ypred=model.predict(X_test_scaled)
ypred
#in dataset target colume values are 0 and 1 , but here output is a continuous number
#because in output function is sigmoid. it gives you o/p in terms of probability
#in sigmoid if probability is >0.5 it gives you 1 and if probabili it <0 it shous give you 0

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 758us/step

array([[0.03496272, 0.02320675, 0.04113021, ..., 0.06845967, 0.03972061,
        0.0429222 ],
       [0.03041209, 0.01646907, 0.06014397, ..., 0.10884874, 0.0567642 ,
        0.04643719],
       [0.06414343, 0.02018585, 0.03240192, ..., 0.03373874, 0.01391474,
        0.03009135],
       ...,
       [0.03944533, 0.02062503, 0.06146267, ..., 0.03279348, 0.04147385,
        0.02346353],
       [0.01574974, 0.02255844, 0.04413505, ..., 0.10216834, 0.03769377,
        0.03610229],
       [0.0238016 , 0.01371862, 0.03689137, ..., 0.02400687, 0.02539789,
        0.01883896]], dtype=float32)

In [49]:
y_test

array([19, 11,  0, ..., 16, 24, 24])

In [50]:
ypred>0.5 # not it will give me 1or 0 OR true or false answer

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [51]:
ypred = ypred >0.5
ypred

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [52]:
y_test

array([19, 11,  0, ..., 16, 24, 24])

In [58]:
ypred_classes = np.argmax(model.predict(X_test_scaled), axis=1)
print(classification_report(y_test, ypred_classes))

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
              precision    recall  f1-score   support

           0       0.29      0.13      0.18       149
           1       0.00      0.00      0.00       153
           2       0.15      0.23      0.19       137
           3       0.00      0.00      0.00       156
           4       0.03      0.01      0.02       141
           5       0.00      0.00      0.00       140
           6       0.14      0.09      0.11       160
           7       0.04      0.06      0.05       144
           8       0.00      0.00      0.00       146
           9       0.00      0.00      0.00       149
          10       0.02      0.12      0.03       130
          11       0.00      0.00      0.00       155
          12       0.02      0.01      0.02       168
          13       0.00      0.00      0.00       151
          14       0.00      0.00      0.00       145
          15       0.00      0.00      0.00       173
          16       0.00      0.00      0.00       166
          17       0.02      0.03      0.02       160
          18       0.00      0.00      0.00       171
          19       0.09      0.01      0.01       163
          20       0.00      0.00      0.00       183
          21       0.01      0.04      0.02       158
          22       0.01      0.03      0.02       148
          23       0.03      0.08      0.04       154
          24       0.00      0.00      0.00       168
          25       0.00      0.00      0.00       132

    accuracy                           0.03      4000
   macro avg       0.03      0.03      0.03      4000
weighted avg       0.03      0.03      0.03      4000

#3. Hyperparameter Tuning

●	Modify various hyperparameters, such as the number of hidden layers, neurons per hidden layer, activation functions, and learning rate, to observe their
impact on model performance.

●	Adopt a structured approach like grid search or random search for hyperparameter tuning, documenting your methodology thoroughly.

In [55]:
!pip install -U keras-tuner

Requirement already satisfied: keras-tuner in /usr/local/lib/python3.12/dist-packages (1.4.8)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.0.5)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.80.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.2.25)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)

In [56]:
# tunning the ANN model

import keras_tuner as kt

In [57]:
def optimizer_selection(hp):
  model=Sequential() #creating instance od sequence class

  model.add(Dense(units=64, activation='relu', input_dim=X_train_scaled.shape[1])) # Add a hidden layer
  model.add(Dense(units=num_classes, activation='softmax')) # Add output layer for multi-class classification
  optim=hp.Choice('optimizer',values=['sgd','adam','rmsprop']) #optimizerselection
  model.compile(optimizer=optim,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

  return model

In [65]:
import shutil #The shutil module offers a number of high-level operations on files and collections of files, including copying, moving, and deleting.
shutil.rmtree('untitled_project', ignore_errors=True) #to ignore errors that might occur during the removal process,
tuner = kt.RandomSearch(optimizer_selection,objective='val_accuracy',max_trials=3)

In [68]:
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 3 Complete [00h 00m 19s]
val_accuracy: 0.9135000109672546

Best val_accuracy So Far: 0.9135000109672546
Total elapsed time: 00h 00m 51s

In [61]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'sgd'}

In [69]:
model=tuner.get_best_models(num_models=1)[0]
model.fit(X_train_scaled,y_train,epochs=100,validation_data=(X_test_scaled,y_test))

Epoch 1/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9274 - loss: 0.2521 - val_accuracy: 0.9118 - val_loss: 0.2874
Epoch 2/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9308 - loss: 0.2432 - val_accuracy: 0.9105 - val_loss: 0.2912
Epoch 3/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9321 - loss: 0.2368 - val_accuracy: 0.9153 - val_loss: 0.2804
Epoch 4/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9345 - loss: 0.2300 - val_accuracy: 0.9165 - val_loss: 0.2755
Epoch 5/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9371 - loss: 0.2236 - val_accuracy: 0.9165 - val_loss: 0.2701
Epoch 6/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9376 - loss: 0.2189 - val_accuracy: 0.9180 - val_loss: 0.2662
Epoch 7/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9379 - loss: 0.2134 - val_accuracy: 0.9218 - val_loss: 0.2605
Epoch 8/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9409 - loss: 0.2084 - val_accuracy: 0.9172 - val_loss: 0.2583
Epoch 9/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9427 - loss: 0.2034 - val_accuracy: 0.9243 - val_loss: 0.2531
Epoch 10/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9440 - loss: 0.1995 - val_accuracy: 0.9200 - val_loss: 0.2555
Epoch 11/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9444 - loss: 0.1947 - val_accuracy: 0.9193 - val_loss: 0.2519
Epoch 12/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9458 - loss: 0.1915 - val_accuracy: 0.9212 - val_loss: 0.2474
Epoch 13/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9464 - loss: 0.1878 - val_accuracy: 0.9258 - val_loss: 0.2381
Epoch 14/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9471 - loss: 0.1838 - val_accuracy: 0.9237 - val_loss: 0.2421
Epoch 15/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9485 - loss: 0.1809 - val_accuracy: 0.9305 - val_loss: 0.2361
Epoch 16/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9493 - loss: 0.1773 - val_accuracy: 0.9255 - val_loss: 0.2364
Epoch 17/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9491 - loss: 0.1742 - val_accuracy: 0.9300 - val_loss: 0.2298
Epoch 18/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9515 - loss: 0.1705 - val_accuracy: 0.9268 - val_loss: 0.2300
Epoch 19/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9508 - loss: 0.1685 - val_accuracy: 0.9312 - val_loss: 0.2270
Epoch 20/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9525 - loss: 0.1660 - val_accuracy: 0.9340 - val_loss: 0.2259
Epoch 21/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9528 - loss: 0.1623 - val_accuracy: 0.9325 - val_loss: 0.2244
Epoch 22/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9534 - loss: 0.1594 - val_accuracy: 0.9298 - val_loss: 0.2287
Epoch 23/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9541 - loss: 0.1577 - val_accuracy: 0.9295 - val_loss: 0.2211
Epoch 24/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9545 - loss: 0.1555 - val_accuracy: 0.9315 - val_loss: 0.2203
Epoch 25/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9560 - loss: 0.1527 - val_accuracy: 0.9325 - val_loss: 0.2219
Epoch 26/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9556 - loss: 0.1506 - val_accuracy: 0.9340 - val_loss: 0.2163
Epoch 27/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9569 - loss: 0.1474 - val_accuracy: 0.9325 - val_loss: 0.2162
Epoch 28/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9581 - loss: 0.1463 - val_accuracy: 0.9345 - val_loss: 0.2172
Epoch 29/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9569 - loss: 0.1444 - val_accuracy: 0.9337 - val_loss: 0.2142
Epoch 30/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9588 - loss: 0.1422 - val_accuracy: 0.9340 - val_loss: 0.2132
Epoch 31/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9594 - loss: 0.1397 - val_accuracy: 0.9335 - val_loss: 0.2127
Epoch 32/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9591 - loss: 0.1385 - val_accuracy: 0.9337 - val_loss: 0.2098
Epoch 33/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9592 - loss: 0.1370 - val_accuracy: 0.9350 - val_loss: 0.2092
Epoch 34/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9606 - loss: 0.1347 - val_accuracy: 0.9348 - val_loss: 0.2086
Epoch 35/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9613 - loss: 0.1327 - val_accuracy: 0.9348 - val_loss: 0.2075
Epoch 36/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9614 - loss: 0.1314 - val_accuracy: 0.9352 - val_loss: 0.2065
Epoch 37/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9621 - loss: 0.1298 - val_accuracy: 0.9337 - val_loss: 0.2066
Epoch 38/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9619 - loss: 0.1283 - val_accuracy: 0.9345 - val_loss: 0.2052
Epoch 39/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9631 - loss: 0.1262 - val_accuracy: 0.9375 - val_loss: 0.2006
Epoch 40/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9625 - loss: 0.1248 - val_accuracy: 0.9355 - val_loss: 0.2043
Epoch 41/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9636 - loss: 0.1242 - val_accuracy: 0.9337 - val_loss: 0.2030
Epoch 42/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9641 - loss: 0.1227 - val_accuracy: 0.9360 - val_loss: 0.2009
Epoch 43/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9647 - loss: 0.1207 - val_accuracy: 0.9377 - val_loss: 0.1995
Epoch 44/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9644 - loss: 0.1199 - val_accuracy: 0.9385 - val_loss: 0.1984
Epoch 45/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9654 - loss: 0.1184 - val_accuracy: 0.9360 - val_loss: 0.1980
Epoch 46/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9643 - loss: 0.1168 - val_accuracy: 0.9392 - val_loss: 0.1957
Epoch 47/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9653 - loss: 0.1161 - val_accuracy: 0.9395 - val_loss: 0.1945
Epoch 48/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9664 - loss: 0.1146 - val_accuracy: 0.9388 - val_loss: 0.1955
Epoch 49/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9671 - loss: 0.1141 - val_accuracy: 0.9390 - val_loss: 0.1938
Epoch 50/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9667 - loss: 0.1122 - val_accuracy: 0.9367 - val_loss: 0.1914
Epoch 51/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9675 - loss: 0.1112 - val_accuracy: 0.9402 - val_loss: 0.1930
Epoch 52/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.1102 - val_accuracy: 0.9398 - val_loss: 0.1924
Epoch 53/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9678 - loss: 0.1084 - val_accuracy: 0.9405 - val_loss: 0.1963
Epoch 54/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.1076 - val_accuracy: 0.9380 - val_loss: 0.1931
Epoch 55/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9670 - loss: 0.1076 - val_accuracy: 0.9425 - val_loss: 0.1911
Epoch 56/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9696 - loss: 0.1050 - val_accuracy: 0.9390 - val_loss: 0.1976
Epoch 57/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9697 - loss: 0.1044 - val_accuracy: 0.9388 - val_loss: 0.1909
Epoch 58/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9688 - loss: 0.1037 - val_accuracy: 0.9433 - val_loss: 0.1938
Epoch 59/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9680 - loss: 0.1028 - val_accuracy: 0.9417 - val_loss: 0.1889
Epoch 60/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9704 - loss: 0.1022 - val_accuracy: 0.9415 - val_loss: 0.1858
Epoch 61/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9701 - loss: 0.1008 - val_accuracy: 0.9427 - val_loss: 0.1917
Epoch 62/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9701 - loss: 0.1000 - val_accuracy: 0.9433 - val_loss: 0.1881
Epoch 63/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9711 - loss: 0.0985 - val_accuracy: 0.9405 - val_loss: 0.1905
Epoch 64/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9699 - loss: 0.0981 - val_accuracy: 0.9427 - val_loss: 0.1869
Epoch 65/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9722 - loss: 0.0966 - val_accuracy: 0.9442 - val_loss: 0.1890
Epoch 66/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9718 - loss: 0.0965 - val_accuracy: 0.9433 - val_loss: 0.1818
Epoch 67/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9718 - loss: 0.0959 - val_accuracy: 0.9445 - val_loss: 0.1842
Epoch 68/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9724 - loss: 0.0947 - val_accuracy: 0.9417 - val_loss: 0.1837
Epoch 69/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9727 - loss: 0.0939 - val_accuracy: 0.9430 - val_loss: 0.1866
Epoch 70/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9723 - loss: 0.0929 - val_accuracy: 0.9430 - val_loss: 0.1830
Epoch 71/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9735 - loss: 0.0922 - val_accuracy: 0.9445 - val_loss: 0.1838
Epoch 72/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9732 - loss: 0.0914 - val_accuracy: 0.9457 - val_loss: 0.1812
Epoch 73/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9734 - loss: 0.0905 - val_accuracy: 0.9440 - val_loss: 0.1809
Epoch 74/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9748 - loss: 0.0896 - val_accuracy: 0.9450 - val_loss: 0.1834
Epoch 75/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9731 - loss: 0.0892 - val_accuracy: 0.9440 - val_loss: 0.1822
Epoch 76/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9753 - loss: 0.0878 - val_accuracy: 0.9452 - val_loss: 0.1811
Epoch 77/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9753 - loss: 0.0877 - val_accuracy: 0.9457 - val_loss: 0.1847
Epoch 78/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9739 - loss: 0.0867 - val_accuracy: 0.9465 - val_loss: 0.1843
Epoch 79/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9747 - loss: 0.0866 - val_accuracy: 0.9452 - val_loss: 0.1828
Epoch 80/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9753 - loss: 0.0854 - val_accuracy: 0.9463 - val_loss: 0.1844
Epoch 81/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9746 - loss: 0.0850 - val_accuracy: 0.9435 - val_loss: 0.1844
Epoch 82/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9752 - loss: 0.0845 - val_accuracy: 0.9423 - val_loss: 0.1867
Epoch 83/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9741 - loss: 0.0840 - val_accuracy: 0.9455 - val_loss: 0.1794
Epoch 84/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9758 - loss: 0.0823 - val_accuracy: 0.9448 - val_loss: 0.1852
Epoch 85/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9758 - loss: 0.0824 - val_accuracy: 0.9445 - val_loss: 0.1840
Epoch 86/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9758 - loss: 0.0815 - val_accuracy: 0.9440 - val_loss: 0.1833
Epoch 87/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9764 - loss: 0.0809 - val_accuracy: 0.9427 - val_loss: 0.1848
Epoch 88/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9769 - loss: 0.0800 - val_accuracy: 0.9450 - val_loss: 0.1816
Epoch 89/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9768 - loss: 0.0801 - val_accuracy: 0.9463 - val_loss: 0.1843
Epoch 90/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9766 - loss: 0.0787 - val_accuracy: 0.9455 - val_loss: 0.1820
Epoch 91/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9771 - loss: 0.0785 - val_accuracy: 0.9452 - val_loss: 0.1789
Epoch 92/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9771 - loss: 0.0782 - val_accuracy: 0.9465 - val_loss: 0.1846
Epoch 93/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9778 - loss: 0.0769 - val_accuracy: 0.9475 - val_loss: 0.1805
Epoch 94/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9768 - loss: 0.0768 - val_accuracy: 0.9467 - val_loss: 0.1824
Epoch 95/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9772 - loss: 0.0762 - val_accuracy: 0.9448 - val_loss: 0.1811
Epoch 96/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9776 - loss: 0.0761 - val_accuracy: 0.9448 - val_loss: 0.1819
Epoch 97/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9778 - loss: 0.0748 - val_accuracy: 0.9460 - val_loss: 0.1816
Epoch 98/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9778 - loss: 0.0746 - val_accuracy: 0.9465 - val_loss: 0.1798
Epoch 99/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9792 - loss: 0.0730 - val_accuracy: 0.9452 - val_loss: 0.1819
Epoch 100/100
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9789 - loss: 0.0735 - val_accuracy: 0.9470 - val_loss: 0.1806

In [64]:
model.evaluate(X_test_scaled,y_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.0305 - loss: 3.4326

[3.4325976371765137, 0.030500000342726707]

In [70]:
model.evaluate(X_train_scaled,y_train)

500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.9818 - loss: 0.0668

[0.06684720516204834, 0.9818124771118164]

4. Evaluation

●	Employ suitable metrics such as accuracy, precision, recall, and F1-score to evaluate your model's performance.

●	Discuss the performance differences between the model with default hyperparameters and the tuned model, emphasizing the effects of hyperparameter tuning.

### Evaluation of the Tuned Model

In [73]:
# Evaluate the tuned model on the test set
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f"\nTuned Model Test Loss: {loss:.4f}")
print(f"Tuned Model Test Accuracy: {accuracy:.4f}")

# Make predictions on the test set
y_pred_tuned_probs = model.predict(X_test_scaled)
y_pred_tuned_classes = np.argmax(y_pred_tuned_probs, axis=1)

# Classification Report: Includes precision, recall, f1-score, and support for each class
print("\nClassification Report for Tuned Model:\n")
print(classification_report(y_test, y_pred_tuned_classes, target_names=label_encoder.classes_))

# Confusion Matrix: Provides a detailed breakdown of correct and incorrect classifications
print("\nConfusion Matrix for Tuned Model:\n")
conf_matrix = confusion_matrix(y_test, y_pred_tuned_classes)
display(pd.DataFrame(conf_matrix, index=label_encoder.classes_, columns=label_encoder.classes_))

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9470 - loss: 0.1806

Tuned Model Test Loss: 0.1806
Tuned Model Test Accuracy: 0.9470
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 784us/step

Classification Report for Tuned Model:

              precision    recall  f1-score   support

           A       0.97      0.98      0.97       149
           B       0.94      0.93      0.93       153
           C       0.95      0.92      0.93       137
           D       0.92      0.94      0.93       156
           E       0.91      0.95      0.93       141
           F       0.95      0.90      0.93       140
           G       0.95      0.94      0.95       160
           H       0.88      0.85      0.87       144
           I       0.96      0.95      0.96       146
           J       0.97      0.96      0.96       149
           K       0.88      0.93      0.90       130
           L       0.96      0.97      0.96       155
           M       0.97      0.97      0.97       168
           N       0.96      0.90      0.93       151
           O       0.89      0.97      0.93       145
           P       0.97      0.94      0.95       173
           Q       0.98      0.96      0.97       166
           R       0.88      0.91      0.90       160
           S       0.98      0.98      0.98       171
           T       0.96      0.98      0.97       163
           U       0.94      0.96      0.95       183
           V       0.93      0.96      0.95       158
           W       0.98      0.95      0.97       148
           X       0.95      0.97      0.96       154
           Y       0.99      0.96      0.97       168
           Z       0.98      0.98      0.98       132

    accuracy                           0.95      4000
   macro avg       0.95      0.95      0.95      4000
weighted avg       0.95      0.95      0.95      4000


Confusion Matrix for Tuned Model:

,A,B,C,D,E,F,G,H,I,J,...,Q,R,S,T,U,V,W,X,Y,Z
A,146,1,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
B,0,142,0,1,1,0,0,1,0,0,...,0,5,0,0,0,2,0,0,0,0
C,0,0,126,0,2,0,3,0,0,0,...,0,0,0,1,0,1,0,0,0,0
D,0,0,0,146,0,0,0,6,0,1,...,0,0,0,0,0,0,0,0,0,0
E,0,1,2,0,134,0,2,0,1,0,...,0,0,0,0,0,0,0,0,0,1
F,0,0,0,1,1,126,0,0,1,0,...,0,0,2,1,0,2,0,2,0,0
G,0,0,1,1,1,0,151,0,0,0,...,1,1,0,0,0,2,1,0,0,0
H,0,1,0,4,1,0,0,123,0,0,...,0,3,0,0,3,0,0,0,0,0
I,0,0,0,1,0,0,0,0,139,1,...,1,0,0,0,0,0,0,3,0,0
J,0,0,0,0,0,0,0,0,3,143,...,0,1,0,0,0,0,0,1,0,0
K,0,0,0,0,1,0,0,3,0,0,...,0,4,0,0,0,0,0,1,0,0
L,0,0,2,0,1,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
M,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
N,1,1,0,1,0,0,0,1,0,0,...,0,2,0,0,2,0,1,0,1,0
O,0,0,1,0,0,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
P,1,1,0,0,1,5,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Q,0,0,0,1,0,0,2,0,0,0,...,159,0,0,0,0,1,0,0,0,0
R,0,3,1,0,2,0,0,2,0,0,...,0,145,0,0,0,1,0,0,0,0
S,0,0,0,0,1,0,0,0,0,0,...,0,0,168,0,0,0,0,0,0,1
T,0,0,0,0,0,0,0,0,0,0,...,0,1,1,160,0,0,0,1,0,0
U,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,176,0,0,0,0,0
V,0,1,0,1,0,1,0,0,0,0,...,0,1,0,1,1,152,0,0,0,0
W,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,1,141,0,0,0
X,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,149,0,0
Y,1,0,0,0,0,0,0,1,0,0,...,0,0,0,4,0,1,0,0,161,0
Z,1,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,129

### Discussion of Performance Differences

**Initial Model (Before Tuning):**

Before hyperparameter tuning, the initial model was compiled with the adadelta optimizer and trained. However, this model exhibited a critical issue: its loss consistently remained nan throughout training, and it achieved an accuracy of approximately 0.04 (random guessing). This indicates that the default setup was completely ineffective, failing to learn any meaningful patterns from the data.

**Tuned Model (After Tuning):**

After employing keras_tuner's Random Search to find the best optimizer, the model built with the best-performing optimizer (sgd) showed significant improvements:

*   **Training and Validation Performance:** During training for 100 epochs, the tuned model achieved a high training accuracy of around 0.98 and a validation accuracy (on X_test_scaled) of approximately 0.94-0.95. This demonstrates that the model was successfully learning from the data and generalizing well to unseen validation samples.
*   **Test Set Performance:** The final evaluation on the dedicated test set yielded an accuracy of approximately 0.94-0.95, a drastic improvement over the initial model. The precision, recall, and F1-score across most classes are significantly higher, indicating that the model can now effectively distinguish between different alphabet letters.

**Impact of Hyperparameter Tuning:**

The hyperparameter tuning process, specifically optimizing the choice of optimizer, had a profound impact:

1.  **Resolved Training Instability:** Switching from adadelta to sgd (as chosen by the tuner) eliminated the nan loss issue, allowing the model to converge and learn.
2.  **Improved Accuracy and Generalization:** The tuned model is robust and performs exceptionally well on unseen data, achieving high accuracy, precision, recall, and F1-scores, which were entirely absent in the untuned version.
3.  **Efficiency:** While only the optimizer was tuned in this specific example, a more extensive tuning process (exploring learning rates, number of layers, neurons, etc.) would further refine performance. Even this limited tuning was sufficient to transform a non-functional model into a highly effective one for this classification task.

In conclusion, hyperparameter tuning was not just an optimization step but a critical component in making the Artificial Neural Network functional and achieving strong performance on the alphabet classification task.